//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.10 at 01:25:29 PM IST 
//


package com.jeya.java;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="line" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="start_time_operation" type="{http://www.w3.org/2001/XMLSchema}time"/>
 *                   &lt;element name="end_time_operation" type="{http://www.w3.org/2001/XMLSchema}time"/>
 *                   &lt;element name="count_vehicles">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *                         &lt;minInclusive value="0"/>
 *                         &lt;maxInclusive value="10"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="map" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="start_station" type="{}station" minOccurs="0"/>
 *                   &lt;element name="end_station" type="{}station" minOccurs="0"/>
 *                   &lt;element name="intermediate_stations" type="{}station" maxOccurs="5" minOccurs="0"/>
 *                   &lt;element name="vehicles_line" maxOccurs="10" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="capacity" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                             &lt;element name="driver" type="{}driver" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                           &lt;attribute ref="{}id use="required""/>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute ref="{}id use="required""/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "line"
})
@XmlRootElement(name = "lvb_system")
public class LvbSystem {

    protected List<LvbSystem.Line> line;

    /**
     * Gets the value of the line property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the line property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLine().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LvbSystem.Line }
     * 
     * 
     */
    public List<LvbSystem.Line> getLine() {
        if (line == null) {
            line = new ArrayList<LvbSystem.Line>();
        }
        return this.line;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="start_time_operation" type="{http://www.w3.org/2001/XMLSchema}time"/>
     *         &lt;element name="end_time_operation" type="{http://www.w3.org/2001/XMLSchema}time"/>
     *         &lt;element name="count_vehicles">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
     *               &lt;minInclusive value="0"/>
     *               &lt;maxInclusive value="10"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="map" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="start_station" type="{}station" minOccurs="0"/>
     *         &lt;element name="end_station" type="{}station" minOccurs="0"/>
     *         &lt;element name="intermediate_stations" type="{}station" maxOccurs="5" minOccurs="0"/>
     *         &lt;element name="vehicles_line" maxOccurs="10" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="capacity" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                   &lt;element name="driver" type="{}driver" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *                 &lt;attribute ref="{}id use="required""/>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute ref="{}id use="required""/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "code",
        "type",
        "startTimeOperation",
        "endTimeOperation",
        "countVehicles",
        "map",
        "startStation",
        "endStation",
        "intermediateStations",
        "vehiclesLine"
    })
    public static class Line {

        @XmlElement(required = true)
        protected String code;
        @XmlElement(required = true)
        protected String type;
        @XmlElement(name = "start_time_operation", required = true)
        @XmlSchemaType(name = "time")
        protected XMLGregorianCalendar startTimeOperation;
        @XmlElement(name = "end_time_operation", required = true)
        @XmlSchemaType(name = "time")
        protected XMLGregorianCalendar endTimeOperation;
        @XmlElement(name = "count_vehicles")
        protected int countVehicles;
        @XmlElement(required = true)
        protected String map;
        @XmlElement(name = "start_station")
        protected Station startStation;
        @XmlElement(name = "end_station")
        protected Station endStation;
        @XmlElement(name = "intermediate_stations")
        protected List<Station> intermediateStations;
        @XmlElement(name = "vehicles_line")
        protected List<LvbSystem.Line.VehiclesLine> vehiclesLine;
        @XmlAttribute(name = "id", required = true)
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger id;

        /**
         * Gets the value of the code property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCode() {
            return code;
        }

        /**
         * Sets the value of the code property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCode(String value) {
            this.code = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the startTimeOperation property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getStartTimeOperation() {
            return startTimeOperation;
        }

        /**
         * Sets the value of the startTimeOperation property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setStartTimeOperation(XMLGregorianCalendar value) {
            this.startTimeOperation = value;
        }

        /**
         * Gets the value of the endTimeOperation property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getEndTimeOperation() {
            return endTimeOperation;
        }

        /**
         * Sets the value of the endTimeOperation property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setEndTimeOperation(XMLGregorianCalendar value) {
            this.endTimeOperation = value;
        }

        /**
         * Gets the value of the countVehicles property.
         * 
         */
        public int getCountVehicles() {
            return countVehicles;
        }

        /**
         * Sets the value of the countVehicles property.
         * 
         */
        public void setCountVehicles(int value) {
            this.countVehicles = value;
        }

        /**
         * Gets the value of the map property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMap() {
            return map;
        }

        /**
         * Sets the value of the map property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMap(String value) {
            this.map = value;
        }

        /**
         * Gets the value of the startStation property.
         * 
         * @return
         *     possible object is
         *     {@link Station }
         *     
         */
        public Station getStartStation() {
            return startStation;
        }

        /**
         * Sets the value of the startStation property.
         * 
         * @param value
         *     allowed object is
         *     {@link Station }
         *     
         */
        public void setStartStation(Station value) {
            this.startStation = value;
        }

        /**
         * Gets the value of the endStation property.
         * 
         * @return
         *     possible object is
         *     {@link Station }
         *     
         */
        public Station getEndStation() {
            return endStation;
        }

        /**
         * Sets the value of the endStation property.
         * 
         * @param value
         *     allowed object is
         *     {@link Station }
         *     
         */
        public void setEndStation(Station value) {
            this.endStation = value;
        }

        /**
         * Gets the value of the intermediateStations property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the intermediateStations property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getIntermediateStations().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Station }
         * 
         * 
         */
        public List<Station> getIntermediateStations() {
            if (intermediateStations == null) {
                intermediateStations = new ArrayList<Station>();
            }
            return this.intermediateStations;
        }

        /**
         * Gets the value of the vehiclesLine property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the vehiclesLine property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getVehiclesLine().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link LvbSystem.Line.VehiclesLine }
         * 
         * 
         */
        public List<LvbSystem.Line.VehiclesLine> getVehiclesLine() {
            if (vehiclesLine == null) {
                vehiclesLine = new ArrayList<LvbSystem.Line.VehiclesLine>();
            }
            return this.vehiclesLine;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setId(BigInteger value) {
            this.id = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="capacity" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *         &lt;element name="driver" type="{}driver" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *       &lt;attribute ref="{}id use="required""/>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name",
            "capacity",
            "driver"
        })
        public static class VehiclesLine {

            @XmlElement(required = true)
            protected String name;
            @XmlElement(required = true)
            protected BigInteger capacity;
            protected List<Driver> driver;
            @XmlAttribute(name = "id", required = true)
            @XmlSchemaType(name = "positiveInteger")
            protected BigInteger id;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the capacity property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getCapacity() {
                return capacity;
            }

            /**
             * Sets the value of the capacity property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setCapacity(BigInteger value) {
                this.capacity = value;
            }

            /**
             * Gets the value of the driver property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the driver property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getDriver().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Driver }
             * 
             * 
             */
            public List<Driver> getDriver() {
                if (driver == null) {
                    driver = new ArrayList<Driver>();
                }
                return this.driver;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setId(BigInteger value) {
                this.id = value;
            }

        }

    }

}
