//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.10 at 01:25:29 PM IST 
//


package com.jeya.java;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.jeya.java package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.jeya.java
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LvbSystem }
     * 
     */
    public LvbSystem createLvbSystem() {
        return new LvbSystem();
    }

    /**
     * Create an instance of {@link LvbSystem.Line }
     * 
     */
    public LvbSystem.Line createLvbSystemLine() {
        return new LvbSystem.Line();
    }

    /**
     * Create an instance of {@link Driver }
     * 
     */
    public Driver createDriver() {
        return new Driver();
    }

    /**
     * Create an instance of {@link Station }
     * 
     */
    public Station createStation() {
        return new Station();
    }

    /**
     * Create an instance of {@link LvbSystem.Line.VehiclesLine }
     * 
     */
    public LvbSystem.Line.VehiclesLine createLvbSystemLineVehiclesLine() {
        return new LvbSystem.Line.VehiclesLine();
    }

}
